services:
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build:
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
  
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
networks:
  inception:
    name: inception